version: 0.2

env:
  variables:
    NEXT_PUBLIC_MST_WEBHOOK_URL: "https://rashadbarnett.app.n8n.cloud/webhook/2570b966-3b9d-4dd6-981d-53cf2a79e2aa"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules
      - npm ci
  build:
    commands:
      - npm run build
      - echo "Syncing static export to S3..."
      - aws s3 cp out/ s3://mstcpatx-s3-poc-bucket/ --recursive
artifacts:
  files:
    - 'out/**/*'